Review sampling bias
b-cubed-eu/gcube pull request #50
Opened 2024-04-04 18:36 UTC by wlangera

@sangovae and @sunray1 I will add the code of @Mmyahaya and me and my review for #48 in this draft PR.
So that you have an idea what I am doing. I will let you know if it is final so you can again review.

2024-04-04 21:15 UTC, wlangera commented
Changes **sample_observations.R**:

- update documentation
   - make conform with other functions of the package
   - remove mentioning SpatRaster object, I will add an issue for this
   - add example (+ visualise)
- add `samping_bias_manual()` function

Changes **apply_polygon_sample_bias.R**:

- update documentation
   - make conform with other functions of the package
   - add example (+ visualise)
-  fix bug matrix to vector

Changes **samping_bias_manual.R**:

- update documentation
   - make conform with other functions of the package
   - add example (+ visualise)
- update checks
   - for every input argument a check
   - check for numeric column bias_weight
   - add check such that numbers larger than 1 are integers

Changes in unit tests:

I just made sure all tests worked. But we need to make more. But lets do that another time ...

2024-04-04 21:25 UTC, sunray1 commented
@wlangera let me know when you are finished making adjustments and I will review

2024-04-05 05:09 UTC, wlangera commented
@sunray1 I am finished :) it is no longer a draft

2024-04-05 08:26 UTC, sangovae approved these changes
I added some more commits to fix little things, not sure if these are also taken in this pull request then?

2024-04-05 08:26 UTC, sunray1 commented
Yes, they have - reviewing now.

2024-04-05 09:14 UTC, sunray1 requested changes
Didn't review the manual files - I imagine they may need to be re-built though.

2024-04-05 09:14 UTC, sunray1 commented on R/sample_observations.R
> +#' # Sample observations with sampling bias in a polygon
```suggestion
#' # Sample observations with sampling bias given manually in a grid
```

2024-04-05 09:14 UTC, sunray1 commented on R/sample_observations.R
> +#' detection probability for each observation (will be the same for all), and a
```suggestion
#' detection probability for each observation (will be the same for all), a
```

2024-04-05 09:14 UTC, sunray1 commented on R/sample_observations.R
>  #' bias, a `sampling_probability` column containing the combined sampling
```suggestion
#' bias, and a `sampling_probability` column containing the combined sampling
```

2024-04-05 09:18 UTC, wlangera commented on R/sampling_bias_manual.R
yes, but lets leave that for now. Can you make an issue for that?

2024-04-05 09:22 UTC, wlangera commented
yes @sunray1 I will pul again from main and rebuild, then I will merge

2024-04-05 09:28 UTC, sunray1 commented on R/sampling_bias_manual.R
See #55

2024-04-05 09:32 UTC, sunray1 approved these changes

2024-04-05 09:32 UTC, merged